<?php

defined( 'ABSPATH' ) || die( 'No script kiddies please!' );

class WordpressLockdowns {

    public function __construct() {
        $this->hooks();
    }

    public function hooks() {
        remove_action('welcome_panel', 'wp_welcome_panel' );
        add_action( 'wp_dashboard_setup', [ $this, 'remove_dashboard_widgets' ] );
        add_action( 'admin_menu',  [$this, 'remove_menus' ] );
        add_action('admin_bar_menu', [ $this, 'remove_from_admin_bar' ], 999 );
        add_filter( 'acf/settings/show_admin', [ $this, 'acf_settings_show_admin' ] );
        add_action( 'admin_init', [ $this, 'redirect_non_admin_user' ] );
        add_action( 'after_setup_theme', [ $this, 'remove_admin_bar' ] );
        
        //disable feeds
        add_action( 'do_feed',      [ $this, 'disable_feeds' ], -1 );
		add_action( 'do_feed_rdf',  [ $this, 'disable_feeds' ], -1 );
		add_action( 'do_feed_rss',  [ $this, 'disable_feeds' ], -1 );
		add_action( 'do_feed_rss2', [ $this, 'disable_feeds' ], -1 );
		add_action( 'do_feed_atom', [ $this, 'disable_feeds' ], -1 );
		// Disable comment feeds.
		add_action( 'do_feed_rss2_comments', 'disable_feeds', -1 );
		add_action( 'do_feed_atom_comments', 'disable_feeds', -1 );
		// Prevent feed links from being inserted in the <head> of the page.
		add_action( 'feed_links_show_posts_feed',    '__return_false', -1 );
		add_action( 'feed_links_show_comments_feed', '__return_false', -1 );
		remove_action( 'wp_head', 'feed_links',       2 );
		remove_action( 'wp_head', 'feed_links_extra', 3 );
    }

    public function remove_dashboard_widgets() {
        global $wp_meta_boxes;
       // unset( $wp_meta_boxes['dashboard']['normal']['core']['dashboard_activity'] );
        unset( $wp_meta_boxes['dashboard']['side']['core']['dashboard_quick_press'] );
        unset( $wp_meta_boxes['dashboard']['normal']['core']['dashboard_incoming_links'] );
        unset( $wp_meta_boxes['dashboard']['normal']['core']['dashboard_right_now'] );
        unset( $wp_meta_boxes['dashboard']['normal']['core']['dashboard_plugins'] );
        unset( $wp_meta_boxes['dashboard']['normal']['core']['dashboard_recent_drafts'] );
        unset( $wp_meta_boxes['dashboard']['normal']['core']['dashboard_recent_comments'] );
        unset( $wp_meta_boxes['dashboard']['side']['core']['dashboard_primary'] );
        unset( $wp_meta_boxes['dashboard']['side']['core']['dashboard_secondary'] );
    }

    public function remove_menus() {
        //remove_menu_page( 'index.php' );                  //Dashboard
        remove_menu_page( 'jetpack' );                    //Jetpack* 
        remove_menu_page( 'edit.php' );                   //Posts
        remove_menu_page( 'upload.php' );                 //Media
        //remove_menu_page( 'edit.php?post_type=page' );    //Pages
        remove_menu_page( 'edit-comments.php' );          //Comments
        remove_menu_page( 'themes.php' );                 //Appearance
        //remove_menu_page( 'plugins.php' );                //Plugins
        //remove_menu_page( 'users.php' );                  //Users
        remove_menu_page( 'tools.php' );                  //Tools
        remove_menu_page( 'options-general.php' );        //Settings
    }

    public function remove_from_admin_bar($wp_admin_bar) {
        // Example of removing item generated by plugin. Full ID is #wp-admin-bar-si_menu
        $wp_admin_bar->remove_node('si_menu');

        // WordPress Core Items (uncomment to remove)
        $wp_admin_bar->remove_node('updates');
        $wp_admin_bar->remove_node('comments');
        $wp_admin_bar->remove_node('new-content');
        //$wp_admin_bar->remove_node('wp-logo');
        //$wp_admin_bar->remove_node('site-name');
        //$wp_admin_bar->remove_node('my-account');
        //$wp_admin_bar->remove_node('search');
        //$wp_admin_bar->remove_node('customize');
        $wp_admin_bar->remove_node('wp-logo');
    }

    public function acf_settings_show_admin( $show_admin ) {
        return true;
    }

    public function redirect_non_admin($redirect_to, $request, $user ){
        $current_user = wp_get_current_user();
        if (user_can( $current_user, 'administrator' )) {

        }
    }

    public function redirect_non_admin_user(){
        if ( is_user_logged_in() ) {
            if ( !defined( 'DOING_AJAX' ) && !current_user_can('administrator') ){
                wp_redirect( site_url() );  
                exit;
            }
        }
    }

    public function remove_admin_bar() {
        if (!current_user_can('administrator') && !is_admin()) {
          show_admin_bar(false);
        }
    }

   public function disable_feeds() {
		wp_redirect( home_url() );
		die;
	}
}

new WordpressLockdowns();
